### ISSUE TITLE
When `UI_URL_PROTOCOL` is set to `https` env files do not generate

### ISSUE THREAD

**Issue by ReidWeb** [mreferre/harbor-setupwrapper#1]
When `UI_URL_PROTOCOL` env var is set to value of `https` the `env` file for the adminserver fails to generate.

**Comment by ReidWeb** [comment]
Fixed issue, needed to set cert path also

**Comment by mreferre** [comment]
@ReidWeb thanks for playing with it. This is interesting... One of the current known limitations is that generating https certificates shouldn't work. Per the current "known limitations" in the main [README](https://github.com/mreferre/harbor-setupwrapper):
```
There will definitely be scenarios where this will break. For example, I haven’t implemented a way to create certificates if you choose to use a secure connection (https). This would need to be additional logic inside harbor-setupwrapper.sh which just doesn’t exist at the time of this writing (hint: do not try to enable https because weird things may happen)
```
Are you trying to "bring your own existing certificates"? I am puzzled (in a good way) :)

**Comment by ReidWeb** [comment]
Hey,

I'm bringing my own certificates - mounting them into the `/data/cert` dir. Interestingly the custom cert and key paths didn't work, had to change their names to be server.crt server.key.

Got it working in the end  by enabling the https option and placing those certs correctly 😄

**Comment by mreferre** [comment]
Thanks for the feedback! This is a workflow I did not even try to test. Glad that it's working!
